/**
 * TypeScript types auto-generated from the Supabase schema.
 * Keep in sync with the SQL migrations in /supabase/migrations/.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// ---------------------------------------------------------------------------
// Row types
// ---------------------------------------------------------------------------

export interface PropertyRow {
  id: string;
  address: string;
  city: string;
  province: string;
  postal_code: string;
  parcel_id: string | null;
  property_type: string;
  assessed_value: number | null;
  year_built: number | null;
  building_size: number | null;
  lot_size: number | null;
  last_sale_date: string | null;
  last_sale_price: number | null;
  is_potential_landlord_property: boolean;
  created_at: string;
}

export interface OwnershipRecordRow {
  id: string;
  property_id: string;
  owner_name: string;
  transfer_date: string | null;
  document_number: string | null;
}

// ---------------------------------------------------------------------------
// Insert types (id and created_at are optional — generated by the DB)
// ---------------------------------------------------------------------------

export type PropertyInsert = Omit<PropertyRow, "id" | "created_at"> & {
  id?: string;
  created_at?: string;
};

export type OwnershipRecordInsert = Omit<OwnershipRecordRow, "id"> & {
  id?: string;
};

// ---------------------------------------------------------------------------
// Database shape expected by the Supabase client generic
// ---------------------------------------------------------------------------

export interface Database {
  public: {
    Tables: {
      properties: {
        Row: PropertyRow;
        Insert: PropertyInsert;
        Update: Partial<PropertyInsert>;
      };
      ownership_records: {
        Row: OwnershipRecordRow;
        Insert: OwnershipRecordInsert;
        Update: Partial<OwnershipRecordInsert>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}

// ---------------------------------------------------------------------------
// Application-level types
// ---------------------------------------------------------------------------

/** Property with its ownership history attached */
export interface PropertyWithOwnership extends PropertyRow {
  ownership_records: OwnershipRecordRow[];
}

/** Filters used on the landlord opportunities dashboard */
export interface PropertyFilters {
  city?: string;
  property_type?: string;
  assessed_value_min?: number;
  assessed_value_max?: number;
}

/** Possible property types used throughout the system */
export const PROPERTY_TYPES = [
  "Single Family",
  "Duplex",
  "Triplex",
  "Fourplex",
  "Apartment Building",
  "Condo",
  "Townhouse",
  "Commercial",
  "Mixed Use",
  "Vacant Land",
  "Other",
] as const;

export type PropertyType = (typeof PROPERTY_TYPES)[number];

/** Multi-unit property types that trigger landlord detection */
export const MULTI_UNIT_TYPES: PropertyType[] = [
  "Duplex",
  "Triplex",
  "Fourplex",
  "Apartment Building",
  "Mixed Use",
];
